### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by renepickhardt** [jnewbery/bitcoin_for_hackers#1]
@conscott suggested your repository in this issue https://github.com/renepickhardt/The-Lightning-Network-Book/issues/9 for my lightning book. Indeed I was about to write my own small ecc python package and I might very well extend on yours - depending on the license. Currently I could not reuse it at all.

**Comment by jnewbery** [comment]
The code in ecc.py is taken from Jimmy Song's Programming Blockchain course here: https://github.com/jimmysong/pb-exercises , which is BSD 2-clause. I've now added a comment to include the copyright and license text. This repo wasn't really meant for wide distribution and I guess was in violation of that license by not including the text, so thanks for prompting me!

BSD 2-clause means you're free to use Jimmy's code in your project as long as you include the copyright and license text. I recommend you also ping him to let him know that you've found it useful!
